### PR TITLE
week 2 work: connect API from front end & homepage outlook

### PR DESCRIPTION
**Pull request by avivi28**
I'm Bear Bear.
Please have a look to my work~
http://52.204.167.98:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Your layout exceed the width of screen in the small to middle screen size. (<1200px) Fit it and leave comment for me to review again.

未命名-2

**Comment by avivi28** [comment]
Dear Pangpang,

I have just fixed this layout problem~
could you please have a look again? Thank you 🐻

**Comment by cwpeng** [comment]
No fix. and your layout of attraction list is worse than original version I think.

未命名-10

**Comment by avivi28** [comment]
I believe it's fine now 🐼

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by avivi28** [comment]
yeeaaaaa 🐨 ! thxxx

**Pull request merged**
