### PR TITLE
Week 1 Mission Completed

### PR DESCRIPTION
**Pull request by avivi28**
I am a Bear. (Chan Hung)
http://52.204.167.98:3000/api/attractions?page=1
http://52.204.167.98:3000/api/attractions?page=0&keyword=藝術
http://52.204.167.98:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
Your URLs are broken. Fix it and leave message for me to review again.

**Comment by avivi28** [comment]
Oh, nohup tracked me. I just fixed it 🐻 
Could you please review again? thx!

**Comment by cwpeng** [comment]
cannot connect still.

**Comment by avivi28** [comment]
I have updated again and try to connect these URLs on other devices. Hope it's workable now 😔

**Comment by cwpeng** [comment]
I cannot connect http://52.204.167.98:3000/api/attractions?page=1. If you think it works now, could you paste a successful testing screenshot with URL included?

**Comment by avivi28** [comment]
Suree! 
this

**Comment by cwpeng** [comment]
Could you paste screenshot of your inbound secure group settings in AWS EC2 console? I try to find out why I can not connect to your server, but you can.

**Comment by avivi28** [comment]
Thank you so much 🐼 
that

**Comment by cwpeng** [comment]
Your source setting is limited to your own device's IP, not any others. A web server should open to everyone in the world. So, change it to 0.0.0.0/0

**Comment by avivi28** [comment]
oh i see!! 😲  I thought it was dangerous to set as 0.0.0.0.
sorry for bothering your time. I hope you can connect it now🙇.
image

**Review by cwpeng — COMMENTED** [review]
It looks almost done but a small issue:
response format of http://52.204.167.98:3000/api/attraction/10 is incorrect, attraction data is not wrapped by an array, you can check API spec carefully to find the difference.

Fix it, create new commit and leave comment for me to review again.

**Pull request closed without merging**
