### PR TITLE
week 7: optimize the project 

### PR DESCRIPTION
**Pull request by avivi28**
I'm bear bear 🐻.
Here's my work of this week.
I have finished the requirements from part 7-1 to part 7-6.
For MVC format, I have just organized the format of backend part only.
Is there any parts that I should be aware of ?

Plz have a look~ Thanks!!
http://52.204.167.98:3000/

### CODE REVIEW

**Comment by avivi28** [comment]
Dear teacher pang pang,

Can you receive this PR? 🐼
I'm wondering did you miss this PR 😢?

**Review by cwpeng — APPROVED** [review]
You have done many good jobs. So, just keep forwarding to your next loving project. :)

I think id.py in model folder is a little strange. I prefer put code in id.py into attraction.py in model folder.

**Comment by avivi28** [comment]
Oh~Thank you so much for your comment 🐻!!
but I did removed the id.py and put it into attraction.py in the third commit🤨.
Maybe github not yet updated?  😲 
image

**Comment by cwpeng** [comment]
Good. My fault of missing that!

**Pull request merged**
